"""Shared generation-request schema (plan §4.1) with Spark-bank import + sampler path.

Both request-production options emit the same records. Banks are replayed from
saved files, never regenerated by assumption.
"""

from __future__ import annotations

import hashlib
import json
import random

REQUEST_SOURCES = ("dataset_derived", "spark_authored", "seeded_sampler")


def validate_request(record: dict) -> list[str]:
    """Return schema errors; empty means the request is importable."""
    errors: list[str] = []
    if not isinstance(record.get("request_id"), str) or not record["request_id"]:
        errors.append("request needs a non-empty string 'request_id'")
    source = record.get("request_source")
    if source not in REQUEST_SOURCES:
        errors.append(f"request_source must be one of {REQUEST_SOURCES}, got {source!r}")
    task = record.get("task")
    if not isinstance(task, dict):
        return errors + ["request needs a mapping 'task'"]
    entities = task.get("entities")
    if not isinstance(entities, list) or not entities:
        errors.append("task needs a non-empty list 'entities'")
    else:
        for i, ent in enumerate(entities):
            if not isinstance(ent, dict) or not ent.get("type") or not ent.get("value"):
                errors.append(f"entities[{i}] needs string 'type' and 'value'")
    constraints = task.get("constraints", {})
    if not isinstance(constraints, dict):
        errors.append("task.constraints must be a mapping when present")
    prompt = record.get("prompt")
    if prompt is not None:
        if not isinstance(prompt, str) or not prompt:
            errors.append("'prompt' must be a non-empty string when present")
        else:
            for ent in entities if isinstance(entities, list) else []:
                value = ent.get("value", "") if isinstance(ent, dict) else ""
                if value and prompt.count(value) != 1:
                    errors.append(
                        f"explicit prompt contradicts entities: {value!r} occurs "
                        f"{prompt.count(value)}x, must occur exactly once"
                    )
    return errors


def render_prompt(record: dict) -> str:
    """Render task fields into the saved prompt (plan §4.1 formatter)."""
    task = record["task"]
    lines = [
        "Write one short realistic message.",
        "Preserve each supplied name exactly as given, exactly once.",
        "Introduce no additional person names.",
        "Return only a JSON object with a 'text' field.",
    ]
    for ent in task["entities"]:
        lines.append(f"Entity {ent['type']}: {ent['value']}")
    context = task.get("context")
    if context:
        lines.append(f"Context: {context}")
    return "\n".join(lines)


def load_bank(path: str, *, provenance: dict) -> dict:
    """Import a JSONL request bank with validation + content hash.

    `provenance` must carry the authoring brief, creator, and creation date —
    the saved bank (not a future regeneration) is the reproducibility artifact.
    """
    for key in ("brief", "created_by", "created_utc"):
        if not provenance.get(key):
            raise ValueError(f"bank provenance needs {key!r}")
    digest = hashlib.sha256()
    records = []
    with open(path, "rb") as f:
        for lineno, line in enumerate(f, 1):
            if not line.strip():
                continue
            digest.update(line)
            try:
                record = json.loads(line)
            except json.JSONDecodeError as e:
                raise ValueError(f"bank line {lineno}: invalid JSON ({e})") from e
            errors = validate_request(record)
            if errors:
                raise ValueError(f"bank line {lineno}: " + "; ".join(errors))
            records.append(record)
    if not records:
        raise ValueError("bank holds no requests")
    return {
        "records": records,
        "manifest": {
            "path": path,
            "sha256": digest.hexdigest(),
            "count": len(records),
            "by_source": sorted({r["request_source"] for r in records}),
            "provenance": provenance,
        },
    }


def seeded_sampler(
    names: list[str],
    *,
    seed: int,
    contexts: tuple[str, ...] = (),
    language: str = "en",
    prefix: str = "seed",
) -> list[dict]:
    """Minimal programmatic path (Option B): same schema, recorded seed."""
    rng = random.Random(seed)
    pool = list(names)
    rng.shuffle(pool)
    requests = []
    for i, name in enumerate(pool):
        task: dict = {
            "language": language,
            "entities": [{"type": "PERSON", "value": name}],
            "constraints": {
                "occurrences_per_entity": 1,
                "no_additional_person_names": True,
            },
        }
        if contexts:
            task["context"] = contexts[i % len(contexts)]
        requests.append(
            {
                "request_id": f"{prefix}-{seed}-{i:04d}",
                "request_source": "seeded_sampler",
                "task": task,
            }
        )
    return requests
